# Generated by Django 2.0.4 on 2018-04-21 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='article',
            new_name='Blog',
        ),
    ]
