# Generated by Django 2.0.4 on 2018-05-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180513_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_publick',
        ),
    ]
